
name: Update Paju News

on:
  schedule:
    - cron: '0 */3 * * *'  # 매 3시간마다
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Install dependencies
        run: pip install requests beautifulsoup4
      - name: Fetch news
        run: python get-news.py
      - name: Commit and push
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'actions@github.com'
          git add news.json
          git commit -m "Update news"
          git push
